version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hifeed-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hifeed
      POSTGRES_PASSWORD: hifeed_secret
      POSTGRES_DB: hifeed_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
